# Generated by Django 2.1.3 on 2018-11-11 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='username',
            new_name='user',
        ),
        migrations.AddField(
            model_name='user',
            name='center',
            field=models.CharField(default='76876876', max_length=200),
            preserve_default=False,
        ),
    ]
